services:
  backend:
    build:
      context: ./backend
    container_name: smashhub_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: smashhub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # frontend (future)
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: smashhub_frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
